before_install:
  - gem update bundler
  - sed -i '1d' Gemfile
before_script:
  - npm install -g mocha-phantomjs@2.0.2
  - bundle exec rake test_js &> /dev/null &
  - sleep 5
cache: bundler
language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
script:
  - bundle exec rspec
  - mocha-phantomjs http://localhost:4567/test
  - bundle exec rubocop
sudo: false
