development:
  adapter: postgresql
  database: stringer_dev
  encoding: unicode
  pool: 5

test:
  adapter: sqlite3
  database: db/stringer_test.sqlite

production:
  url: <%= ENV["DATABASE_URL"] %>
  encoding: unicode
  pool: 5
