#! /bin/bash

echo "--> updating from upstream"
scripts/update_from_upstream

echo "--> updating heroku"
git push heroku master
heroku run rake db:migrate --app rtircher-stringer
heroku restart --app rtircher-stringer
